### PR TITLE
Rebased version of #9 -- forcing adminer download if script is older then 1 day, also adds theme support as well.

### PR DESCRIPTION
**Pull request by robbyoconnor**
This is a squashed version of #9 -- literally just squashed all commits. 

Quoting mostly from #9: 
> This PR adds:
> 
> - support for optional css styling
> - a test on the age of the adminer.css file and forced download if this age is > 1 day and similarly for adminer.php
> - Hope this is fit for inclusion.

### CODE REVIEW

**Comment by robbyoconnor** [comment]
@killua-eu -- I rebased/squashed your commits -- your authorship is retained.

**Comment by killua-eu** [comment]
Oh. Oh! Thanks @robbyoconnor , should have done that a long time ago.

**Comment by robbyoconnor** [comment]
@killua-eu it was an itch I had and I needed it at the time -- so it's my pleasure to always contribute changes back to the FOSS community -- I needed it to cleanly apply when I cherry-picked.

**Comment by robbyoconnor** [comment]
@geerlingguy bumping this

**Comment by robbyoconnor** [comment]
bumping this again @geerlingguy (not a rush, just keeping it from closing)

**Comment by geerlingguy** [comment]
LGTM!

**Comment by robbyoconnor** [comment]
Thank you @geerlingguy <3 

I have a few other PRs in some of your other role repos

**Pull request merged**
